### ISSUE TITLE
"Remember Me" doesn't work

### ISSUE THREAD

**Issue by DanJFletcher** [kerongon/Collabo#14]
**Describe the problem**

When logging in, if you check "remember me", you will still be automatically logged out after 10 min.

**How to reproduce the problem**

Login and check "remember me". Wait 10 min. and see that you've been logged out. (Or change the time to something like 30 seconds to find out faster)

**Comment by kerongon** [comment]
The "remember me" works for front end users. The admin middleware logs users out after 10 minutes for an layer of security.
